- name: Edit journald.conf
  become: true
  community.general.ini_file:
    dest: /etc/systemd/journald.conf
    section: Journal
    option: MaxLevelStore
    value: '{{ journald_log_level }}'
    owner: root
    group: root
    mode: '644'
  notify: journald_restart

- name: Restart systemd-journald if necessary
  ansible.builtin.meta: flush_handlers
