- name: Make journald less noisy
  become: true
  block:
    - name: Edit journald.conf
      community.general.ini_file:
        dest: /etc/systemd/journald.conf
        section: Journal
        option: MaxLevelStore
        value: '{{ journald_log_level }}'
        owner: root
        group: root
        mode: '644'
      register: edited

    - name: Restart systemd-journald
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: systemd-journald
        state: restarted
      when: edited.changed
