dependencies:
  - role: cloud_init_wait
  - role: apt
    vars:
      apt_packages: '{{ debian_cloud_server_packages }}'
      apt_unattended: true
  - role: sshd
  - role: firewall
  - role: linux_status
  - role: journald
