namespace: tensin
name: infra
version: 0.0.16
description: Some common Ansible roles used by me to manage things
repository: https://github.com/egor-tensin/infra-ansible
readme: README.md
license:
  - MIT
authors:
  - Egor Tensin <Egor.Tensin@gmail.com>
