- name: Rate pacman mirrors
  become: true
  ansible.builtin.shell: |
    . /etc/os-release && rate-mirrors \
        --allow-root \
        --disable-comments \
        --save /etc/pacman.d/mirrorlist \
        "$ID"
