- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: systemd_depend_mount_restart

- name: Collect installed services
  ansible.builtin.service_facts:
  listen: systemd_depend_mount_restart

- name: Restart systemd services
  ansible.builtin.include_tasks: service.yml
  listen: systemd_depend_mount_restart
  loop: "{{ systemd_depend_mount_result.results | selectattr('changed', 'equalto', true) | map(attribute='service') | list }}"
  loop_control:
    loop_var: service
