# For some reason, if the key is in a weird format that requires
# running `gpg --dearmor`, you must save it with the .gpg extension
# instead of .asc. You can then completely skip the gpg step. Source:
# https://stackoverflow.com/q/71585303/514684
apt_repo_key_path: '{{ apt_repo_keys_dir }}/{{ apt_repo_name }}{{ apt_repo_key_dearmor | ternary(".gpg", ".asc") }}'
