- name: Get host distro
  ansible.builtin.setup:
    gather_subset: [distribution_release]

- name: Set up PPA repository
  ansible.builtin.include_role:
    name: apt_repo
  vars:
    apt_repo_name: '{{ ppa_name }}'
    apt_repo_key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x{{ ppa_key }}'
    apt_repo_url: 'https://ppa.launchpadcontent.net/{{ ppa_owner }}/{{ ppa_name }}/ubuntu'
    apt_repo_distro: '{{ ppa_distro | default(ansible_distribution_release) }}'
