- name: Show upgraded packages
  ansible.builtin.debug:
    var: pacman_result.packages
  listen: pacman_upgraded

- name: Reboot
  become: true
  ansible.builtin.reboot:
    # 3 minutes is plenty.
    reboot_timeout: 180
  listen: pacman_upgraded
