- name: Set up repository
  become: true
  block:
    - name: Create keys directory
      ansible.builtin.file:
        path: '{{ apt_repo_keys_dir }}'
        mode: '755'
        state: directory

    - name: Set key path
      ansible.builtin.set_fact:
        key_path: '{{ apt_repo_keys_dir }}/{{ apt_repo_name }}.asc'

    - name: 'Add key: {{ apt_repo_name }}'
      ansible.builtin.get_url:
        url: '{{ apt_repo_key_url }}'
        dest: '{{ key_path }}'
        mode: '644'

    - name: 'Add repository: {{ apt_repo_name }}'
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by={{ key_path }}] {{ apt_repo_url }} {{ apt_repo_distro }} {{ apt_repo_component }}'
        filename: '{{ apt_repo_name }}'
