- name: Enable traffic forwarding
  become: true
  ansible.posix.sysctl:
    name: '{{ item }}'
    value: 1
    reload: true
    sysctl_file: '{{ router_sysctl_file }}'
  loop:
    - net.ipv4.ip_forward
    - net.ipv4.conf.all.forwarding
    - net.ipv6.conf.all.forwarding
