- name: Create workspace directory
  become: true
  ansible.builtin.file:
    path: '{{ my_workspace_dir }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '750'

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name:
      - git
      - make
    state: present

- name: Update projects
  ansible.builtin.include_tasks: project.yml
  loop: '{{ my_workspace_projects }}'
  loop_control:
    loop_var: project
