- name: Default mount path
  ansible.builtin.set_fact:
    volume_dir: "{{ volume_dir | default('/mnt/{{ volume_name }}') }}"

- name: Mount volume
  become: true
  ansible.posix.mount:
    path: '{{ volume_dir }}'
    src: '/dev/disk/by-id/scsi-0DO_Volume_{{ volume_name }}'
    state: mounted
    fstype: '{{ volume_fs }}'
    opts: defaults,nofail,discard
