# Instructions are from
#     https://certbot.eff.org/instructions?ws=nginx&os=snap&tab=wildcard

- name: Install Certbot
  become: true
  block:
    - name: Install snapd
      ansible.builtin.apt:
        name: snapd
        state: present
        install_recommends: false

    - name: Install Certbot
      community.general.snap:
        name: certbot
        state: present
        classic: true

    - name: Confirm plugin containment level
      ansible.builtin.command: snap set certbot trust-plugin-with-root=ok

    - name: Install Certbot DigitalOcean plugin
      community.general.snap:
        name: certbot-dns-digitalocean
        state: present

    - name: Create Certbot symlink in /usr/bin
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
